### ISSUE TITLE
Shapefile output

### ISSUE THREAD

**Issue by bmander** [maptrace/architecture#11]
Command line traffic-engine outputs shapfile. The shapefile shall be a linestring shapefile, where objects are tagged with speed statistics.

One significant challenge of this is that each way segment will have 336 attributes - a count and a mean for each hour of the week. 225 is the maximum number of fields for a shapefile. The shapefile would either need to store more coarse statistics - average speed overall, for example - or the shapefile could ship with a variety of id-keyed statistical extract CSVs which one could join to the shapefile in the GIS application of their choice.

**Comment by sbma44** [comment]
What's the target application you have in mind -- postgis? I wonder if it's worth fitting .shp's square peg into this round hole. GeoJSON, maybe?

**Comment by bmander** [comment]
cc195866eb1c100f62adbc66e1b07c2f7e815ab9
